# FBI Hate Crime Data
### Fall 2022 
### Author: Mandy Hong

In [1]:
import os
import sys
import lxml
import math
import numpy as np
import pandas as pd


path_1 = os.path.join('/Users/mandyhong/Desktop', "hate_crime.csv")                  
hc = pd.read_csv(path_1)  
hc

/Users/mandyhong/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,3015,1991,AR0040200,Rogers,NaN,City,AR,Arkansas,West South Central,South,...,White,NaN,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
1,3016,1991,AR0290100,Hope,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Simple Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,S,S
2,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
3,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
4,3017,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Service/Gas Station,Anti-White,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219572,1318026,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,2,Intimidation,2.0,Park/Playground,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
219573,1142103,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,Park/Playground,Anti-White,Government,S,S
219574,1318018,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Black or African American,Not Hispanic or Latino,1,Aggravated Assault,1.0,Residence/Home,Anti-White,Individual,S,S
219575,1318022,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Simple Assault,1.0,Residence/Home,Anti-Female,Individual,S,S
219576,1318023,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Theft From Building,1.0,Residence/Home,Anti-Gender Non-Conforming,Individual,S,S

In [2]:
pd.unique(hc['BIAS_DESC'])
#df1 = df1.rename(columns={'Site ID': 'Site IRN'})

array(['Anti-Black or African American', 'Anti-White', 'Anti-Jewish',
       'Anti-Arab', 'Anti-Protestant', 'Anti-Other Religion',
       'Anti-Islamic (Muslim)', 'Anti-Gay (Male)', 'Anti-Asian',
       'Anti-Catholic', 'Anti-Heterosexual', 'Anti-Hispanic or Latino',
       'Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Multiple Religions, Group', 'Anti-Multiple Races, Group',
       'Anti-Lesbian (Female)',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-American Indian or Alaska Native',
       'Anti-Gay (Male);Anti-White',
       'Anti-Black or African American;Anti-Jewish',
       'Anti-Black or African American;Anti-Lesbian (Female)',
       'Anti-Black or African American;Anti-Gay (Male)',
       'Anti-Black or African American;Anti-White',
       'Anti-Atheism/Agnosticism', 'Anti-Gay (Male);Anti-Jewish',
       'Anti-Bisexual', 'Anti-Hispanic or Latino;Anti-White',
       'Anti-Hispanic or Latino;Anti-Multiple Races, Group',
       'Anti-American Indian or Alaska Native;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Gay (Male);Anti-White',
       'Anti-Asian;Anti-Gay (Male)',
       'Anti-Multiple Races, Group;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Physical Disability',
       'Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Mental Disability',
       'Anti-Asian;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Multiple Races, Group',
       'Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Lesbian (Female);Anti-White',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-White',
       'Anti-Heterosexual;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Multiple Religions, Group;Anti-Other Religion',
       'Anti-Jewish;Anti-White', 'Anti-Arab;Anti-Hispanic or Latino',
       'Anti-Asian;Anti-Black or African American',
       'Anti-American Indian or Alaska Native;Anti-Islamic (Muslim)',
       'Anti-American Indian or Alaska Native;Anti-Asian',
       'Anti-Black or African American;Anti-Protestant',
       'Anti-American Indian or Alaska Native;Anti-Black or African American',
       'Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Jewish;Anti-Multiple Religions, Group',
       'Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Gay (Male);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Hispanic or Latino;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Gay (Male);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Multiple Races, Group;Anti-Other Religion',
       'Anti-Gay (Male);Anti-Multiple Races, Group',
       'Anti-Other Religion;Anti-Protestant',
       'Anti-Islamic (Muslim);Anti-Jewish',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-White',
       'Anti-Bisexual;Anti-Heterosexual', 'Anti-Gender Non-Conforming',
       'Anti-Female', 'Anti-Islamic (Muslim);Anti-Other Religion',
       'Anti-Black or African American;Anti-Islamic (Muslim)',
       'Anti-Transgender', 'Anti-Bisexual;Anti-Black or African American',
       'Anti-Gay (Male);Anti-Lesbian (Female)',
       'Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Gay (Male);Anti-Mental Disability',
       'Anti-Gay (Male);Anti-Islamic (Muslim)', 'Anti-Male',
       'Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Mental Disability;Anti-Physical Disability',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-Other Religion',
       'Anti-Multiple Religions, Group;Anti-Protestant',
       'Anti-Black or African American;Anti-Jewish;Anti-White',
       "Anti-Jehovah's Witness", 'Anti-Mormon', 'Anti-Buddhist',
       'Anti-Sikh', 'Anti-Other Christian', 'Anti-Hindu',
       'Anti-Asian;Anti-Atheism/Agnosticism',
       'Anti-Eastern Orthodox (Russian, Greek, Other)',
       'Anti-Arab;Anti-Black or African American',
       'Anti-Catholic;Anti-Jewish',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Physical Disability',
       'Anti-Bisexual;Anti-Gay (Male)', 'Anti-Other Religion;Anti-White',
       'Anti-Asian;Anti-Female',
       'Anti-Jewish;Anti-Lesbian (Female);Anti-White',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Multiple Races, Group;Anti-White',
       'Anti-Islamic (Muslim);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Gay (Male);Anti-Transgender',
       'Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Gay (Male);Anti-Physical Disability',
       'Anti-Lesbian (Female);Anti-Other Religion',
       'Anti-Gay (Male);Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Arab;Anti-Black or African American;Anti-Islamic (Muslim)',
       'Anti-Arab;Anti-Hispanic or Latino;Anti-Islamic (Muslim)',
       'Anti-Arab;Anti-Islamic (Muslim)', 'Anti-Female;Anti-Gay (Male)',
       'Anti-Asian;Anti-Hispanic or Latino',
       'Anti-Islamic (Muslim);Anti-Multiple Races, Group',
       'Anti-Arab;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Other Religion',
       'Anti-Multiple Races, Group;Anti-White',
       'Anti-Physical Disability;Anti-White',
       'Anti-Black or African American;Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Transgender',
       'Anti-Transgender;Anti-White',
       'Anti-Multiple Religions, Group;Anti-Transgender',
       'Anti-Jewish;Anti-Transgender', 'Anti-Female;Anti-White',
       'Anti-Female;Anti-Mental Disability',
       'Anti-Gay (Male);Anti-Heterosexual',
       'Anti-Catholic;Anti-Protestant',
       'Anti-Mental Disability;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Mental Disability',
       'Anti-Male;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Arab;Anti-Asian;Anti-Black or African American',
       'Anti-Asian;Anti-Islamic (Muslim)',
       'Anti-Hispanic or Latino;Anti-Male',
       'Anti-Black or African American;Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Jewish;Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Jewish;Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Hispanic or Latino;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Male;Anti-White', 'Anti-Jewish;Anti-Lesbian (Female)',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Female;Anti-Mental Disability;Anti-White',
       'Anti-Male;Anti-Multiple Races, Group;Anti-White',
       'Anti-Asian;Anti-White',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Transgender',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Lesbian (Female)',
       "Unknown (offender's motivation not known)",
       'Anti-Gay (Male);Anti-Male',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Jewish',
       'Anti-American Indian or Alaska Native;Anti-White',
       'Anti-Asian;Anti-Multiple Races, Group',
       'Anti-Female;Anti-Hispanic or Latino',
       'Anti-Hispanic or Latino;Anti-Islamic (Muslim)',
       'Anti-Gay (Male);Anti-Hispanic or Latino',
       'Anti-Atheism/Agnosticism;Anti-Jewish',
       'Anti-Gay (Male);Anti-Other Christian',
       'Anti-Black or African American;Anti-Other Christian',
       'Anti-Black or African American;Anti-Mormon',
       'Anti-Female;Anti-Lesbian (Female)',
       'Anti-Gender Non-Conforming;Anti-Transgender',
       'Anti-Other Christian;Anti-Other Religion',
       'Anti-Multiple Religions, Group;Anti-Other Christian;Anti-Other Race/Ethnicity/Ancestry;Anti-Other Religion',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Transgender',
       'Anti-Black or African American;Anti-Physical Disability',
       'Anti-Hispanic or Latino;Anti-Lesbian (Female)',
       'Anti-Lesbian (Female);Anti-Transgender',
       'Anti-American Indian or Alaska Native;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Arab;Anti-Islamic (Muslim);Anti-Multiple Religions, Group',
       'Anti-Asian;Anti-Sikh', 'Anti-Asian;Anti-Hindu',
       'Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry;Anti-White',
       'Anti-Arab;Anti-Gay (Male)',
       'Anti-Female;Anti-Multiple Races, Group',
       'Anti-Gender Non-Conforming;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group;Anti-Transgender',
       'Anti-Female;Anti-Other Religion',
       'Anti-Female;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Jewish;Anti-Lesbian (Female);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Female;Anti-Lesbian (Female)',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Black or African American;Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Islamic (Muslim);Anti-White',
       "Anti-Jehovah's Witness;Anti-Other Race/Ethnicity/Ancestry",
       'Anti-Gay (Male);Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-Protestant',
       'Anti-Black or African American;Anti-Female',
       'Anti-Catholic;Anti-Hispanic or Latino',
       'Anti-Hispanic or Latino;Anti-Other Christian',
       'Anti-Hindu;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Jewish;Anti-Mental Disability;Anti-Multiple Races, Group',
       'Anti-Islamic (Muslim);Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Islamic (Muslim);Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry;Anti-Other Religion',
       'Anti-Jewish;Anti-Other Christian',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Religions, Group',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Gender Non-Conforming;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Arab;Anti-Jewish',
       'Anti-Other Race/Ethnicity/Ancestry;Anti-Sikh',
       'Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Islamic (Muslim);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Catholic;Anti-Multiple Religions, Group',
       'Anti-Catholic;Anti-Female;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Heterosexual;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Jewish;Anti-Multiple Religions, Group',
       'Anti-Gay (Male);Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Asian;Anti-Male;Anti-White', 'Anti-Asian;Anti-Jewish',
       'Anti-Hispanic or Latino;Anti-Mental Disability',
       'Anti-Gay (Male);Anti-Jewish;Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Male',
       'Anti-Hispanic or Latino;Anti-Physical Disability',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Gay (Male);Anti-Gender Non-Conforming;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Heterosexual;Anti-Jewish',
       'Anti-Jewish;Anti-Mental Disability;Anti-Other Race/Ethnicity/Ancestry;Anti-Physical Disability',
       'Anti-Catholic;Anti-Other Christian;Anti-White',
       'Anti-Gender Non-Conforming;Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Catholic;Anti-Other Christian',
       'Anti-American Indian or Alaska Native;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Arab;Anti-Islamic (Muslim);Anti-Jewish',
       'Anti-Arab;Anti-Hispanic or Latino;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Asian;Anti-Gay (Male);Anti-Jewish',
       'Anti-Bisexual;Anti-Gay (Male);Anti-Transgender',
       'Anti-Female;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-White',
       'Anti-Heterosexual;Anti-Transgender', 'Anti-Arab;Anti-White',
       'Anti-Islamic (Muslim);Anti-Mental Disability',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Hispanic or Latino',
       'Anti-Gay (Male);Anti-Hispanic or Latino;Anti-Male',
       'Anti-Asian;Anti-Black or African American;Anti-Islamic (Muslim)',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Hispanic or Latino;Anti-Multiple Races, Group',
       'Anti-Arab;Anti-Black or African American;Anti-Hispanic or Latino;Anti-Jewish',
       'Anti-Asian;Anti-Black or African American;Anti-Gay (Male)',
       'Anti-Female;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-American Indian or Alaska Native;Anti-Black or African American;Anti-Hispanic or Latino;Anti-Jewish;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Arab;Anti-Islamic (Muslim);Anti-Male',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Male',
       'Anti-Female;Anti-Gay (Male);Anti-Jewish;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Mental Disability;Anti-Multiple Races, Group;Anti-Multiple Religions, Group;Anti-Physical Disability',
       'Anti-Jewish;Anti-Mental Disability;Anti-White',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Gender Non-Conforming',
       'Anti-Multiple Religions, Group;Anti-White',
       'Anti-Multiple Religions, Group;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Black or African American;Anti-Islamic (Muslim);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Heterosexual;Anti-Islamic (Muslim);Anti-Multiple Races, Group',
       'Anti-Arab;Anti-Sikh',
       'Anti-Black or African American;Anti-Hispanic or Latino;Anti-Islamic (Muslim)',
       'Anti-Hispanic or Latino;Anti-Other Religion',
       'Anti-Black or African American;Anti-Female;Anti-Gay (Male);Anti-Lesbian (Female);Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Arab;Anti-Asian',
       'Anti-Asian;Anti-Black or African American;Anti-Multiple Races, Group',
       'Anti-Asian;Anti-Black or African American;Anti-Gay (Male);Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Multiple Religions, Group',
       'Anti-Asian;Anti-Black or African American;Anti-Female;Anti-Jewish;Anti-Multiple Races, Group',
       'Anti-Black or African American;Anti-Catholic',
       'Anti-Female;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Multiple Races, Group;Anti-Multiple Religions, Group',
       'Anti-Arab;Anti-Black or African American;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Islamic (Muslim);Anti-Jewish;Anti-Lesbian (Female)',
       'Anti-Black or African American;Anti-Multiple Races, Group;Anti-White',
       'Anti-Gay (Male);Anti-Gender Non-Conforming',
       'Anti-Asian;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Multiple Races, Group;Anti-Other Christian',
       'Anti-Protestant;Anti-White',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Islamic (Muslim)',
       'Anti-Black or African American;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Bisexual;Anti-Jewish',
       'Anti-Lesbian (Female);Anti-Other Christian;Anti-White',
       'Anti-Hindu;Anti-Islamic (Muslim);Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Heterosexual;Anti-White',
       'Anti-Black or African American;Anti-Gay (Male);Anti-Transgender',
       'Anti-Female;Anti-Sikh',
       'Anti-Asian;Anti-Black or African American;Anti-Female;Anti-Hispanic or Latino;Anti-Other Race/Ethnicity/Ancestry',
       'Anti-Mental Disability;Anti-White',
       "Anti-Gender Non-Conforming;Anti-Jehovah's Witness",
       'Anti-Jewish;Anti-Other Religion',
       'Anti-Gender Non-Conforming;Anti-White',
       'Anti-Asian;Anti-Black or African American;Anti-Hispanic or Latino',
       'Anti-Black or African American;Anti-Gender Non-Conforming',
       'Anti-Bisexual;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Black or African American;Anti-Multiple Religions, Group;Anti-Native Hawaiian or Other Pacific Islander',
       'Anti-Asian;Anti-Black or African American;Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)',
       'Anti-Hispanic or Latino;Anti-Native Hawaiian or Other Pacific Islander'],
      dtype=object)

In [3]:
hc.loc[hc['MULTIPLE_BIAS'] == "M"] #total 1019 rows with multiple bias

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
635,662,1991,MA0091100,Cambridge,NaN,City,MA,Massachusetts,New England,Northeast,...,White,NaN,2,Robbery;Simple Assault,1.0,Other/Unknown,Anti-Gay (Male);Anti-White,Individual,M,M
672,689,1991,MA0130100,Boston,NaN,City,MA,Massachusetts,New England,Northeast,...,White,NaN,2,Intimidation;Robbery,1.0,Other/Unknown,Anti-Black or African American;Anti-Jewish,Individual,M,M
679,696,1991,MA0130100,Boston,NaN,City,MA,Massachusetts,New England,Northeast,...,White,NaN,2,Destruction/Damage/Vandalism of Property;Robbery,1.0,Other/Unknown,Anti-Black or African American;Anti-Lesbian (F...,Individual,M,M
765,3259,1991,MA0130100,Boston,NaN,City,MA,Massachusetts,New England,Northeast,...,White,NaN,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Other/Unknown,Anti-Gay (Male);Anti-White,Individual,M,M
778,3272,1991,MA0130100,Boston,NaN,City,MA,Massachusetts,New England,Northeast,...,Asian,NaN,2,Intimidation;Simple Assault,1.0,Other/Unknown,Anti-Black or African American;Anti-Gay (Male),Individual,M,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219276,1337753,2020,WASPD0000,Seattle,NaN,City,WA,Washington,Pacific,West,...,Black or African American,Unknown,1,Intimidation,1.0,Residence/Home,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,M
219292,1337816,2020,WASPD0000,Seattle,NaN,City,WA,Washington,Pacific,West,...,White,Unknown,1,Aggravated Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American;Anti-Hispanic o...,Individual,S,M
219299,1337838,2020,WASPD0000,Seattle,NaN,City,WA,Washington,Pacific,West,...,Multiple,Unknown,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Arab;Anti-Gay (Male),Individual,S,M
219315,1337884,2020,WASPD0000,Seattle,NaN,City,WA,Washington,Pacific,West,...,White,Unknown,1,Intimidation,1.0,Residence/Home,Anti-Gay (Male);Anti-Jewish,Individual,S,M
219362,1342229,2020,WI0130800,University of Wisconsin:,Madison,University or College,WI,Wisconsin,East North Central,Midwest,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,School-College/University,"Anti-Jewish;Anti-Multiple Races, Group",Business,S,M

In [4]:
#data with single biased hate crime
hc_s=hc.loc[hc['MULTIPLE_BIAS'] == "S"]
pd.unique(hc_s["BIAS_DESC"])
hc_s #total 218558 rows

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,3015,1991,AR0040200,Rogers,NaN,City,AR,Arkansas,West South Central,South,...,White,NaN,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
1,3016,1991,AR0290100,Hope,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Simple Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,S,S
2,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
3,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
4,3017,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Service/Gas Station,Anti-White,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219572,1318026,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,2,Intimidation,2.0,Park/Playground,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
219573,1142103,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,Park/Playground,Anti-White,Government,S,S
219574,1318018,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Black or African American,Not Hispanic or Latino,1,Aggravated Assault,1.0,Residence/Home,Anti-White,Individual,S,S
219575,1318022,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Simple Assault,1.0,Residence/Home,Anti-Female,Individual,S,S
219576,1318023,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Theft From Building,1.0,Residence/Home,Anti-Gender Non-Conforming,Individual,S,S

In [5]:
#data with racial hate crime
race_category=["Anti-American Indian or Alaska Native", "Anti-Arab", "Anti-Asian", "Anti-Black or African American", "Anti-Native Hawaiian" or "Other Pacific Islander", "Anti-Hispanic or Latino", "Anti-Multiple Races, Group", "Anti-Other Race/Ethnicity/Ancestry", "Anti-White"]
len(race_category)
df=hc_s.copy()
race_hc_s=df.loc[hc_s['BIAS_DESC'].isin(race_category)]
race_hc_s

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,3015,1991,AR0040200,Rogers,NaN,City,AR,Arkansas,West South Central,South,...,White,NaN,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
1,3016,1991,AR0290100,Hope,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Simple Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,S,S
2,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
3,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
4,3017,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Service/Gas Station,Anti-White,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219567,705009,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Intimidation,1.0,Park/Playground,Anti-Black or African American,Individual,S,S
219569,1009279,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,2,Aggravated Assault,2.0,Hotel/Motel/Etc.,Anti-Black or African American,Individual,S,S
219570,1009280,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Simple Assault,1.0,Hotel/Motel/Etc.,Anti-Black or African American,Individual,S,S
219573,1142103,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,Park/Playground,Anti-White,Government,S,S
219574,1318018,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Black or African American,Not Hispanic or Latino,1,Aggravated Assault,1.0,Residence/Home,Anti-White,Individual,S,S

In [6]:
#create racial hate crime data for time series
#aggregate data by month-year
#thus, create a column that has both year and month
list(hc.columns)
hc['INCIDENT_DATE'].head
#hc['DATA_YEAR'].head

<bound method NDFrame.head of 0         31-AUG-91
1         19-SEP-91
2         04-JUL-91
3         24-DEC-91
4         23-DEC-91
            ...
219572    29-NOV-20
219573    14-JUL-20
219574    16-OCT-20
219575    30-JAN-20
219576    21-NOV-20
Name: INCIDENT_DATE, Length: 219577, dtype: object>

In [7]:
race_hc_s.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 140062 entries, 0 to 219574
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   INCIDENT_ID               140062 non-null  int64
 1   DATA_YEAR                 140062 non-null  int64
 2   ORI                       140062 non-null  object
 3   PUB_AGENCY_NAME           140062 non-null  object
 4   PUB_AGENCY_UNIT           3908 non-null    object
 5   AGENCY_TYPE_NAME          140062 non-null  object
 6   STATE_ABBR                140062 non-null  object
 7   STATE_NAME                140062 non-null  object
 8   DIVISION_NAME             140062 non-null  object
 9   REGION_NAME               140062 non-null  object
 10  POPULATION_GROUP_CODE     140062 non-null  object
 11  POPULATION_GROUP_DESC     140062 non-null  object
 12  INCIDENT_DATE             140062 non-null  object
 13  ADULT_VICTIM_COUNT        30702 non-null   float64
 14  JUVENILE_VICTIM_COUNT     29594 non-null   float64
 15  TOTAL_OFFENDER_COUNT      140062 non-null  int64
 16  ADULT_OFFENDER_COUNT      27977 non-null   float64
 17  JUVENILE_OFFENDER_COUNT   27972 non-null   float64
 18  OFFENDER_RACE             140049 non-null  object
 19  OFFENDER_ETHNICITY        20829 non-null   object
 20  VICTIM_COUNT              140062 non-null  int64
 21  OFFENSE_NAME              140062 non-null  object
 22  TOTAL_INDIVIDUAL_VICTIMS  138905 non-null  float64
 23  LOCATION_NAME             140062 non-null  object
 24  BIAS_DESC                 140062 non-null  object
 25  VICTIM_TYPES              140062 non-null  object
 26  MULTIPLE_OFFENSE          140062 non-null  object
 27  MULTIPLE_BIAS             140062 non-null  object
dtypes: float64(5), int64(4), object(19)
memory usage: 31.0+ MB

In [8]:
#extract month from the date
df=race_hc_s.copy()
race_hc_s['INCIDENT_MONTH'] = df.apply(lambda x : x['INCIDENT_DATE'].split("-")[1],axis=1)
race_hc_s['INCIDENT_MONTH'][1]

'SEP'

In [9]:
#extract year from the date
race_hc_s['INCIDENT_YEAR'] = df.apply(lambda x : x['INCIDENT_DATE'].split("-")[2],axis=1)
#race_hc_s['INCIDENT_YEAR']=race_hc_s['INCIDENT_YEAR'].astype('int')
pd.unique(race_hc_s["INCIDENT_YEAR"])

array(['91', '92', '93', '94', '95', '96', '97', '98', '99', '00', '01',
       '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20'], dtype=object)

In [10]:
pd.unique(race_hc_s["INCIDENT_YEAR"])

array(['91', '92', '93', '94', '95', '96', '97', '98', '99', '00', '01',
       '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20'], dtype=object)

In [11]:
#double check if DATA_YEAR is same as INCIDENT_YEAR
l=(race_hc_s['DATA_YEAR'].astype(str).str[2:4]==race_hc_s['INCIDENT_YEAR'].astype(str))
(l==True).count()

140062

In [12]:
#change string type month into integer month
month = {'JAN':1, 'FEB':2, 'MAR':3, 'APR':4, 'MAY':5, "JUN":6, "JUL":7, "AUG":8, "SEP":9, "OCT":10, "NOV":11, "DEC":12 }
race_hc_s.INCIDENT_MONTH = race_hc_s.INCIDENT_MONTH.map(month)
race_hc_s["INCIDENT_MONTH"]

0          8
1          9
2          7
3         12
4         12
          ..
219567     2
219569     8
219570     8
219573     7
219574    10
Name: INCIDENT_MONTH, Length: 140062, dtype: int64

## TIME SERIES DATA : hate crime, year, month

### 1. All race

In [13]:
#make data that only has state, data_year, month left
all_race = race_hc_s[['DATA_YEAR', 'INCIDENT_MONTH']].copy()
all_race.index = range(len(all_race))
all_race

        DATA_YEAR  INCIDENT_MONTH
0            1991               8
1            1991               9
2            1991               7
3            1991              12
4            1991              12
...           ...             ...
140057       2020               2
140058       2020               8
140059       2020               8
140060       2020               7
140061       2020              10

[140062 rows x 2 columns]

In [14]:
#for each year, aggregate by month
#first, create 1991 data as base + test run for loop for month
yearL=pd.unique(all_race["DATA_YEAR"])
i=0
all_race_ts = pd.DataFrame(columns=['year','month','hate_crime']) #create data frame for each year with 12 months
l=all_race.loc[all_race['DATA_YEAR']==yearL[i], "INCIDENT_MONTH"]
#month=1
for month in range(1,13):
    all_race_ts.loc[month-1] = [yearL[i], month, sum(l==month)]
all_race_ts

    year month hate_crime
0   1991     1        198
1   1991     2        204
2   1991     3        218
3   1991     4        233
4   1991     5        280
5   1991     6        261
6   1991     7        350
7   1991     8        359
8   1991     9        340
9   1991    10        360
10  1991    11        253
11  1991    12        207

In [15]:
yearL=yearL[1:30] #list updated without base year, 1991
yearL

array([1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [16]:
print(yearL[28])
print(len(yearL))

2020
29

In [17]:
for year in range(0,29): #for loop using index number, thus need to do last index of the list+1=length of the list
    #print(yearL[year])
    l=all_race.loc[all_race['DATA_YEAR']==yearL[year], "INCIDENT_MONTH"]
    for month in range(1,13):
        df=pd.DataFrame(columns=['year','month','hate_crime'])
        df.loc[month-1] = [yearL[year], month, sum(l==month)]
        all_race_ts = all_race_ts.append(df, ignore_index=True)

In [18]:
all_race_ts #30 years x 12 months =360 rows

     year month hate_crime
0    1991     1        198
1    1991     2        204
2    1991     3        218
3    1991     4        233
4    1991     5        280
..    ...   ...        ...
355  2020     8        694
356  2020     9        608
357  2020    10        613
358  2020    11        464
359  2020    12        361

[360 rows x 3 columns]

In [19]:
outputfile1=os.path.join('/Users/mandyhong/Desktop', 'all_race_hc_ts.csv')
ts_df1=all_race_ts.to_csv(outputfile1, index=False)

### 2. Anti-Black or African American hate crime

In [20]:
#data with Anti-Black or African American racial hate crime
#make data that only has state, data_year, month left
all_race_v2 = race_hc_s[['DATA_YEAR', 'INCIDENT_MONTH', 'BIAS_DESC']].copy()
all_race_v2.index = range(len(all_race_v2))
all_race_v2

        DATA_YEAR  INCIDENT_MONTH                       BIAS_DESC
0            1991               8  Anti-Black or African American
1            1991               9                      Anti-White
2            1991               7  Anti-Black or African American
3            1991              12                      Anti-White
4            1991              12                      Anti-White
...           ...             ...                             ...
140057       2020               2  Anti-Black or African American
140058       2020               8  Anti-Black or African American
140059       2020               8  Anti-Black or African American
140060       2020               7                      Anti-White
140061       2020              10                      Anti-White

[140062 rows x 3 columns]

In [21]:
df=all_race_v2.copy()
black_hc=df.loc[all_race_v2['BIAS_DESC']=="Anti-Black or African American"]
black_hc

        DATA_YEAR  INCIDENT_MONTH                       BIAS_DESC
0            1991               8  Anti-Black or African American
2            1991               7  Anti-Black or African American
11           1991              10  Anti-Black or African American
12           1991               1  Anti-Black or African American
14           1991               2  Anti-Black or African American
...           ...             ...                             ...
140054       2020               7  Anti-Black or African American
140055       2020               6  Anti-Black or African American
140057       2020               2  Anti-Black or African American
140058       2020               8  Anti-Black or African American
140059       2020               8  Anti-Black or African American

[74762 rows x 3 columns]

In [22]:
#for each year, aggregate by month
#first, create 1991 data as base + test run for loop for month
yearL=pd.unique(black_hc["DATA_YEAR"])
i=0
black_hc_ts = pd.DataFrame(columns=['year','month','hate_crime']) #create data frame for each year with 12 months
l=black_hc.loc[black_hc['DATA_YEAR']==yearL[i], "INCIDENT_MONTH"]
#month=1
for month in range(1,13):
    black_hc_ts.loc[month-1] = [yearL[i], month, sum(l==month)]
black_hc_ts

    year month hate_crime
0   1991     1         88
1   1991     2        103
2   1991     3        116
3   1991     4        107
4   1991     5        141
5   1991     6        115
6   1991     7        180
7   1991     8        178
8   1991     9        170
9   1991    10        189
10  1991    11        138
11  1991    12         99

In [26]:
print(len(yearL))
yearL=yearL[1:30]
print(yearL[28])

30
2020

In [23]:
for year in range(0,29): #for loop using index number, thus need to do last index of the list+1=length of the list
    #print(yearL[year])
    l=black_hc.loc[black_hc['DATA_YEAR']==yearL[year], "INCIDENT_MONTH"]
    for month in range(1,13):
        df=pd.DataFrame(columns=['year','month','hate_crime'])
        df.loc[month-1] = [yearL[year], month, sum(l==month)]
        black_hc_ts = black_hc_ts.append(df, ignore_index=True)
black_hc_ts

     year month hate_crime
0    1991     1         88
1    1991     2        103
2    1991     3        116
3    1991     4        107
4    1991     5        141
..    ...   ...        ...
355  2019     8        209
356  2019     9        216
357  2019    10        184
358  2019    11        175
359  2019    12        165

[360 rows x 3 columns]

In [24]:
outputfile2=os.path.join('/Users/mandyhong/Desktop', 'black_hc_ts.csv')
ts_df2=black_hc_ts.to_csv(outputfile2,index=False)

In [25]:
print(black_hc_ts["hate_crime"].sum())

72865

### 3. Anti-Asian hate crime

In [26]:
df=all_race_v2.copy()
asian_hc=df.loc[all_race_v2['BIAS_DESC']=="Anti-Asian"]
asian_hc

        DATA_YEAR  INCIDENT_MONTH   BIAS_DESC
32           1991              11  Anti-Asian
40           1991              12  Anti-Asian
44           1991               8  Anti-Asian
50           1991               8  Anti-Asian
90           1991               6  Anti-Asian
...           ...             ...         ...
139869       2020              11  Anti-Asian
139906       2020               9  Anti-Asian
139922       2020               1  Anti-Asian
139936       2020               3  Anti-Asian
139949       2020               9  Anti-Asian

[6424 rows x 3 columns]

In [27]:
#for each year, aggregate by month
#first, create 1991 data as base + test run for loop for month
yearL=pd.unique(asian_hc["DATA_YEAR"])
i=0
asian_hc_ts = pd.DataFrame(columns=['year','month','hate_crime']) #create data frame for each year with 12 months
l=asian_hc.loc[asian_hc['DATA_YEAR']==yearL[i], "INCIDENT_MONTH"]
#month=1
for month in range(1,13):
    asian_hc_ts.loc[month-1] = [yearL[i], month, sum(l==month)]
asian_hc_ts

    year month hate_crime
0   1991     1          9
1   1991     2          9
2   1991     3         15
3   1991     4         23
4   1991     5         17
5   1991     6         23
6   1991     7         25
7   1991     8         36
8   1991     9         36
9   1991    10         36
10  1991    11         21
11  1991    12         19

In [28]:
print(len(yearL))
yearL=yearL[1:30]
print(yearL[28])

30
2020

In [29]:
for year in range(0,29): #for loop using index number, thus need to do last index of the list+1=length of the list
    #print(yearL[year])
    l=asian_hc.loc[asian_hc['DATA_YEAR']==yearL[year], "INCIDENT_MONTH"]
    #print(len(l))
    for month in range(1,13):
        df=pd.DataFrame(columns=['year','month','hate_crime'])
        df.loc[month-1] = [yearL[year], month, sum(l==month)]
        #print(df.agg({"hate_crime":"mean"}))
        asian_hc_ts = asian_hc_ts.append(df, ignore_index=True)
asian_hc_ts

     year month hate_crime
0    1991     1          9
1    1991     2          9
2    1991     3         15
3    1991     4         23
4    1991     5         17
..    ...   ...        ...
355  2020     8         19
356  2020     9         22
357  2020    10         23
358  2020    11         15
359  2020    12         16

[360 rows x 3 columns]

In [30]:
print(asian_hc_ts["hate_crime"].sum())

6424

In [31]:
outputfile3=os.path.join('/Users/mandyhong/Desktop', 'asian_hc_ts.csv')
ts_df3=asian_hc_ts.to_csv(outputfile3, index=False)

# STATE DATA: hate crimes by state

### 1. All race

In [32]:
#only five years data: 2020, 2019, 2018, 2017, 2016
hcDF=hc_s.loc[hc['DATA_YEAR'].isin([2020, 2019, 2018, 2017, 2016])]
hcDF #38082 rows

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
180618,186845,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,White,Unknown,1,Simple Assault,1.0,School-Elementary/Secondary,Anti-Black or African American,Individual,S,S
180619,186846,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,Black or African American,Unknown,1,Simple Assault,1.0,Service/Gas Station,Anti-Asian,Individual,S,S
180620,186847,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,White,Unknown,1,Aggravated Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
180621,186848,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,Unknown,Unknown,1,Intimidation,1.0,Commercial/Office Building,Anti-American Indian or Alaska Native,Individual,S,S
180622,186849,2016,AK0010300,Juneau,NaN,City,AK,Alaska,Pacific,West,...,American Indian or Alaska Native,Not Hispanic or Latino,1,Simple Assault,1.0,Other/Unknown,Anti-White,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219572,1318026,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,2,Intimidation,2.0,Park/Playground,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
219573,1142103,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,Park/Playground,Anti-White,Government,S,S
219574,1318018,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Black or African American,Not Hispanic or Latino,1,Aggravated Assault,1.0,Residence/Home,Anti-White,Individual,S,S
219575,1318022,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Simple Assault,1.0,Residence/Home,Anti-Female,Individual,S,S
219576,1318023,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Theft From Building,1.0,Residence/Home,Anti-Gender Non-Conforming,Individual,S,S

In [33]:
df1 = hcDF.copy()
df1.index = range(len(df1))
df1

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,186845,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,White,Unknown,1,Simple Assault,1.0,School-Elementary/Secondary,Anti-Black or African American,Individual,S,S
1,186846,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,Black or African American,Unknown,1,Simple Assault,1.0,Service/Gas Station,Anti-Asian,Individual,S,S
2,186847,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,White,Unknown,1,Aggravated Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
3,186848,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,Unknown,Unknown,1,Intimidation,1.0,Commercial/Office Building,Anti-American Indian or Alaska Native,Individual,S,S
4,186849,2016,AK0010300,Juneau,NaN,City,AK,Alaska,Pacific,West,...,American Indian or Alaska Native,Not Hispanic or Latino,1,Simple Assault,1.0,Other/Unknown,Anti-White,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38077,1318026,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,2,Intimidation,2.0,Park/Playground,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
38078,1142103,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,Park/Playground,Anti-White,Government,S,S
38079,1318018,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Black or African American,Not Hispanic or Latino,1,Aggravated Assault,1.0,Residence/Home,Anti-White,Individual,S,S
38080,1318022,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Simple Assault,1.0,Residence/Home,Anti-Female,Individual,S,S
38081,1318023,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Theft From Building,1.0,Residence/Home,Anti-Gender Non-Conforming,Individual,S,S

In [34]:
#aggregate by state
#first, create Alaska data as base + test run for loop for each state
stateL=pd.unique(hcDF["STATE_ABBR"])
yearL=[2016, 2017, 2018, 2019, 2020]
i=0 #for stateL
#j=0 #for yearL
#colL=list(hcDF.columns.values)
state_hc = pd.DataFrame(columns=["state", "year", "hate_crime"]) #create data frame for each year with 12 months
state_hc

l=df1.loc[df1['STATE_ABBR']==stateL[i]] #only select AK state data
for j in range(0,5):
    l_2=l.loc[df1['DATA_YEAR']==yearL[j]]
    state_hc.loc[j]=[stateL[i],yearL[j],len(l_2)]
state_hc

  state  year hate_crime
0    AK  2016         11
1    AK  2017          4
2    AK  2018          5
3    AK  2019         11
4    AK  2020         10

In [35]:
len(stateL)
stateL=stateL[1:52]
stateL

array(['AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'IA',
       'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN',
       'MO', 'MS', 'MT', 'NB', 'NC', 'ND', 'NH', 'NJ', 'NM', 'NV', 'NY',
       'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY', 'FS', 'HI'], dtype=object)

In [36]:
len(stateL)

51

In [37]:
#i=0 #for stateL
for i in range(0,len(stateL)):
    state = pd.DataFrame(columns=["state", "year", "hate_crime"]) #create data frame for each year with 12 months
    #state

    l=df1.loc[df1['STATE_ABBR']==stateL[i]] #only select AK state data
    for j in range(0,5):
        l_2=l.loc[df1['DATA_YEAR']==yearL[j]]
        state.loc[j]=[stateL[i],yearL[j],len(l_2)]
    state_hc=state_hc.append(state)
state_hc

   state  year hate_crime
0     AK  2016         11
1     AK  2017          4
2     AK  2018          5
3     AK  2019         11
4     AK  2020         10
..   ...   ...        ...
0     HI  2016          0
1     HI  2017          0
2     HI  2018         44
3     HI  2019         40
4     HI  2020         36

[260 rows x 3 columns]

In [38]:
print(state_hc["hate_crime"].sum())

38082

In [39]:
outputfile4=os.path.join('/Users/mandyhong/Desktop', 'state_hc_five_years.csv')
hc_df1=state_hc.to_csv(outputfile4, index=False)

In [40]:
#aggregate by state
#first, create Alaska data as base + test run for loop for each state
stateL=pd.unique(state_hc["state"])
i=0 #for stateL
#j=0 #for yearL
#colL=list(hcDF.columns.values)
state_hc2 = pd.DataFrame(columns=["state", "hate_crime"]) #create data frame for each year with 12 months
state_hc2

l=state_hc.loc[state_hc['state']==stateL[i]] #only select AK state data
state_hc2.loc[i]=[stateL[i],l['hate_crime'].sum()]
state_hc2

  state hate_crime
0    AK         41

In [41]:
for i in range(1, len(stateL)):
    l=state_hc.loc[state_hc['state']==stateL[i]] #only select AK state data
    state_hc2.loc[i]=[stateL[i],l['hate_crime'].sum()]

state_hc2

   state hate_crime
0     AK         41
1     AL         55
2     AR        122
3     AZ       1078
4     CA       5433
5     CO        782
6     CT        486
7     DC        878
8     DE        100
9     FL        616
10    GA        500
11    IA         72
12    ID        160
13    IL        433
14    IN        543
15    KS        403
16    KY       1110
17    LA        199
18    MA       1827
19    MD        243
20    ME        195
21    MI       2123
22    MN        714
23    MO        479
24    MS        135
25    MT        117
26    NB        255
27    NC       1057
28    ND         79
29    NH        102
30    NJ       3330
31    NM        195
32    NV        273
33    NY       2749
34    OH       2107
35    OK        180
36    OR        831
37    PA        341
38    RI         67
39    SC        357
40    SD         90
41    TN        681
42    TX       1709
43    UT        243
44    VA        849
45    VT        210
46    WA       2349
47    WI        334
48    WV        300
49    WY         30
50    FS        400
51    HI        120

In [42]:
print(state_hc2['hate_crime'].sum())

38082

In [43]:
outputfile5=os.path.join('/Users/mandyhong/Desktop', 'state_hc.csv')
hc_df2=state_hc2.to_csv(outputfile5, index=False)

### 2. Anti-Black or African American and anti-Asian hate crime data

In [44]:
df2=df1.loc[hc['BIAS_DESC']== "Anti-Black or African American"]
df2 #14140 rows

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,186845,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,White,Unknown,1,Simple Assault,1.0,School-Elementary/Secondary,Anti-Black or African American,Individual,S,S
2,186847,2016,AK0010100,Anchorage,NaN,City,AK,Alaska,Pacific,West,...,White,Unknown,1,Aggravated Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
11,180588,2016,AL0010200,Birmingham,NaN,City,AL,Alabama,East South Central,South,...,White,Unknown,1,Simple Assault,1.0,Department/Discount Store,Anti-Hispanic or Latino,Individual,S,S
12,180589,2016,AL0010200,Birmingham,NaN,City,AL,Alabama,East South Central,South,...,White,Unknown,1,Intimidation,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
15,180592,2016,AL0010200,Birmingham,NaN,City,AL,Alabama,East South Central,South,...,Unknown,Unknown,1,Intimidation,1.0,Parking/Drop Lot/Garage,"Anti-Multiple Religions, Group",Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38076,1318019,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Simple Assault,1.0,Bar/Nightclub,Anti-Other Religion,Individual,S,S
38077,1318026,2020,WY0170100,Sheridan,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,2,Intimidation,2.0,Park/Playground,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
38078,1142103,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,0.0,Park/Playground,Anti-White,Government,S,S
38080,1318022,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Simple Assault,1.0,Residence/Home,Anti-Female,Individual,S,S
38081,1318023,2020,WY0210100,Evanston,NaN,City,WY,Wyoming,Mountain,West,...,White,Not Hispanic or Latino,1,Theft From Building,1.0,Residence/Home,Anti-Gender Non-Conforming,Individual,S,S

In [45]:
#aggregate by state
#first, create Alaska data as base + test run for loop for each state
stateL=pd.unique(df2["STATE_ABBR"])
yearL=[2016, 2017, 2018, 2019, 2020]
i=0 #for stateL
#j=0 #for yearL
#colL=list(hcDF.columns.values)
black_state_hc = pd.DataFrame(columns=["state", "year", "hate_crime"]) #create data frame for each year with 12 months
black_state_hc

l=df2.loc[df2['STATE_ABBR']==stateL[i]] #only select AK state data
for j in range(0,5):
    l_2=l.loc[df2['DATA_YEAR']==yearL[j]]
    black_state_hc.loc[j]=[stateL[i],yearL[j],len(l_2)]
black_state_hc

  state  year hate_crime
0    AK  2016          2
1    AK  2017          2
2    AK  2018          2
3    AK  2019          3
4    AK  2020          3

In [46]:
#i=0 #for stateL
for i in range(1,len(stateL)):
    state = pd.DataFrame(columns=["state", "year", "hate_crime"]) #create data frame for each year with 12 months
    #state

    l=df2.loc[df2['STATE_ABBR']==stateL[i]] #only select AK state data
    for j in range(0,5):
        l_2=l.loc[df2['DATA_YEAR']==yearL[j]]
        state.loc[j]=[stateL[i],yearL[j],len(l_2)]
    black_state_hc=black_state_hc.append(state)
black_state_hc

   state  year hate_crime
0     AK  2016          2
1     AK  2017          2
2     AK  2018          2
3     AK  2019          3
4     AK  2020          3
..   ...   ...        ...
0     HI  2016          0
1     HI  2017          0
2     HI  2018         20
3     HI  2019          5
4     HI  2020         14

[260 rows x 3 columns]

In [47]:
print(black_state_hc["hate_crime"].sum())

14140

In [48]:
outputfile6=os.path.join('/Users/mandyhong/Desktop', 'black_state_hc_five_years.csv')
hc_df3=black_state_hc.to_csv(outputfile6, index=False)

In [49]:
#aggregate by state
#first, create Alaska data as base + test run for loop for each state
stateL=pd.unique(black_state_hc["state"])
i=0 #for stateL
#j=0 #for yearL
#colL=list(hcDF.columns.values)
black_state_hc2 = pd.DataFrame(columns=["state", "hate_crime"]) #create data frame for each year with 12 months
black_state_hc2

l=black_state_hc.loc[black_state_hc['state']==stateL[i]] #only select AK state data
black_state_hc2.loc[i]=[stateL[i],l['hate_crime'].sum()]
black_state_hc2

for i in range(1, len(stateL)):
    l=black_state_hc.loc[black_state_hc['state']==stateL[i]] #only select AK state data
    black_state_hc2.loc[i]=[stateL[i],l['hate_crime'].sum()]

black_state_hc2

   state hate_crime
0     AK         12
1     AL         25
2     AR         54
3     AZ        396
4     CA       2272
5     CO        288
6     CT        156
7     DC        326
8     DE         32
9     FL        213
10    GA        133
11    IA         24
12    ID         53
13    IL        168
14    IN        215
15    KS        165
16    KY        361
17    LA         76
18    MA        602
19    MD         56
20    ME         75
21    MI        743
22    MN        273
23    MO        167
24    MS         57
25    MT         47
26    NB        101
27    NC        386
28    ND         25
29    NH         48
30    NJ       1302
31    NM         66
32    NV         87
33    NY       1088
34    OH        709
35    OK         63
36    OR        287
37    PA        127
38    RI         15
39    SC        125
40    SD         31
41    TN        237
42    TX        661
43    UT        100
44    VA        255
45    VT         65
46    WA        885
47    WI        166
48    WV        159
49    WY         18
50    FS        106
51    HI         39

In [50]:
print(black_state_hc2['hate_crime'].sum())

14140

In [51]:
outputfile7=os.path.join('/Users/mandyhong/Desktop', 'black_state_hc.csv')
hc_df4=black_state_hc2.to_csv(outputfile7, index=False)

In [52]:
#Anti-Asian data
df3=df1.loc[hc['BIAS_DESC']== "Anti-Asian"]
df3 #1591 rows

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
43,180608,2016,AZ0070500,Chandler,NaN,City,AZ,Arizona,Mountain,West,...,Unknown,NaN,4,Intimidation,4.0,Residence/Home,Anti-Jewish,Individual,S,S
55,180619,2016,AZ0072300,Phoenix,NaN,City,AZ,Arizona,Mountain,West,...,Black or African American,NaN,1,Simple Assault,1.0,Residence/Home,Anti-Jewish,Individual,S,S
63,180627,2016,AZ0072300,Phoenix,NaN,City,AZ,Arizona,Mountain,West,...,White,NaN,1,Intimidation,1.0,Other/Unknown,Anti-Gay (Male),Individual,S,S
71,180635,2016,AZ0072300,Phoenix,NaN,City,AZ,Arizona,Mountain,West,...,Unknown,NaN,2,Intimidation,2.0,Residence/Home,Anti-Hispanic or Latino,Individual,S,S
116,180680,2016,AZ0072300,Phoenix,NaN,City,AZ,Arizona,Mountain,West,...,White,NaN,1,Simple Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Asian,Individual,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37887,1331569,2020,WI0220500,Platteville,NaN,City,WI,Wisconsin,East North Central,Midwest,...,White,Unknown,1,Intimidation,1.0,Field/Woods,Anti-Black or African American,Individual,S,S
37966,1331643,2020,WI0610000,Taylor,NaN,County,WI,Wisconsin,East North Central,Midwest,...,Unknown,Unknown,1,Identity Theft,1.0,Residence/Home,Anti-White,Individual,S,S
37969,1331633,2020,WI0680400,New Berlin,NaN,City,WI,Wisconsin,East North Central,Midwest,...,Unknown,Unknown,1,Destruction/Damage/Vandalism of Property,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Gender Non-Conforming,Individual,S,S
37974,1331651,2020,WI0710200,Neenah,NaN,City,WI,Wisconsin,East North Central,Midwest,...,Unknown,Unknown,1,Theft From Motor Vehicle,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Sikh,Individual,S,S
38032,1121395,2020,WV0540100,Parkersburg,NaN,City,WV,West Virginia,South Atlantic,South,...,Unknown,Unknown,1,Robbery,1.0,Residence/Home,"Anti-Multiple Races, Group",Individual,S,S

In [53]:
#aggregate by state
#first, create Alaska data as base + test run for loop for each state
stateL=pd.unique(df3["STATE_ABBR"])
yearL=[2016, 2017, 2018, 2019, 2020]
i=0 #for stateL
#j=0 #for yearL
#colL=list(hcDF.columns.values)
asian_state_hc = pd.DataFrame(columns=["state", "year", "hate_crime"]) #create data frame for each year with 12 months
asian_state_hc

l=df3.loc[df3['STATE_ABBR']==stateL[i]] #only select AK state data
for j in range(0,5):
    l_2=l.loc[df3['DATA_YEAR']==yearL[j]]
    asian_state_hc.loc[j]=[stateL[i],yearL[j],len(l_2)]
asian_state_hc

  state  year hate_crime
0    AZ  2016         11
1    AZ  2017         20
2    AZ  2018         13
3    AZ  2019          8
4    AZ  2020          9

In [54]:
#i=0 #for stateL
for i in range(1,len(stateL)):
    state = pd.DataFrame(columns=["state", "year", "hate_crime"]) #create data frame for each year with 12 months
    #state

    l=df3.loc[df3['STATE_ABBR']==stateL[i]] #only select AK state data
    for j in range(0,5):
        l_2=l.loc[df3['DATA_YEAR']==yearL[j]]
        state.loc[j]=[stateL[i],yearL[j],len(l_2)]
    asian_state_hc=asian_state_hc.append(state)
asian_state_hc

   state  year hate_crime
0     AZ  2016         11
1     AZ  2017         20
2     AZ  2018         13
3     AZ  2019          8
4     AZ  2020          9
..   ...   ...        ...
0     MD  2016          0
1     MD  2017          0
2     MD  2018          0
3     MD  2019          0
4     MD  2020          1

[260 rows x 3 columns]

In [55]:
print(asian_state_hc["hate_crime"].sum())

1591

In [56]:
outputfile8=os.path.join('/Users/mandyhong/Desktop', 'asian_state_hc_five_years.csv')
hc_df5=asian_state_hc.to_csv(outputfile8, index=False)

In [57]:
#aggregate by state
#first, create Alaska data as base + test run for loop for each state
stateL=pd.unique(asian_state_hc["state"])
i=0 #for stateL
#j=0 #for yearL
#colL=list(hcDF.columns.values)
asian_state_hc2 = pd.DataFrame(columns=["state", "hate_crime"]) #create data frame for each year with 12 months
asian_state_hc2

l=asian_state_hc.loc[asian_state_hc['state']==stateL[i]] #only select AK state data
asian_state_hc2.loc[i]=[stateL[i],l['hate_crime'].sum()]
asian_state_hc2

for i in range(1, len(stateL)):
    l=asian_state_hc.loc[asian_state_hc['state']==stateL[i]] #only select AK state data
    asian_state_hc2.loc[i]=[stateL[i],l['hate_crime'].sum()]

asian_state_hc2

   state hate_crime
0     AZ         61
1     CA        232
2     CO         26
3     CT         28
4     DC         18
5     FL         18
6     GA          7
7     IA          6
8     ID          4
9     IL         14
10    IN         17
11    KS         11
12    KY         42
13    LA          6
14    MA         63
15    NC         47
16    NH          4
17    NJ        184
18    NM         15
19    NV         22
20    NY        165
21    OH        129
22    OK         11
23    OR         47
24    PA         13
25    SC         14
26    TX         60
27    VA         29
28    VT          4
29    WA         82
30    WI         17
31    WV         12
32    WY          1
33    AK          2
34    AL          4
35    AR          1
36    DE          4
37    MI         52
38    MN         22
39    MO         18
40    MS          3
41    ND          5
42    TN         39
43    UT          7
44    FS          3
45    HI          5
46    NB          5
47    SD          2
48    ME          3
49    MT          3
50    RI          3
51    MD          1

In [58]:
print(asian_state_hc2['hate_crime'].sum())

1591

In [59]:
outputfile9=os.path.join('/Users/mandyhong/Desktop', 'asian_state_hc.csv')
hc_df6=asian_state_hc2.to_csv(outputfile9, index=False)